### ISSUE TITLE
Columbus day defaults to 2021 date causing countdown to be 0

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/content-templates#101]
Columbus day defaults to 2021 date causing the countdown to be 0. 

Update to 2022 fixes this problem, update default to 2022. 

![image](https://user-images.githubusercontent.com/100098797/191284340-6cfd6304-59c9-4882-b120-4976744f5530.png)

**Comment by osmankarame** [comment]
@cameronreidrisevision this is fixed Thanks!
