### ISSUE TITLE
Famous Athletes Quotes template freezing and exiting Rise player on FireOS

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/content-templates#102]
https://www.risevision.com/template-details/auto-update-famous-athletes 

This template is crashing on FireOS. It freezes the display at times and exits the player to the home menu.

I have been able to replicate this.

**Comment by ezequielc** [comment]
I think I narrowed it down to the background video (fire.mp4) :
https://user-images.githubusercontent.com/7738553/200053427-2d39587d-7df6-4490-b79e-cfeb87f90c66.mp4

When I play the video in a Fullscreen Video Template  on my Firestick (Lite), it crashes everytime.

I tried the same with the Video Widget and it ran without issues. Thanks

**Comment by santiagonoguez** [comment]
@ezequielc should Creative use rise-video for that background, or should this scenario could be attended on Delivery's next epic, thanks !

**Comment by ezequielc** [comment]
@santiagonoguez They already use rise-video. I am wondering if for now Creative could upload a lower resolution version of that video and see if that fixes the problem for the short term. @mmeiers Do you agree? Thanks

**Comment by osmankarame** [comment]
@ezequielc I uploaded a lower resolution video to see if it fixes the problem.

**Comment by ezequielc** [comment]
@osmankarame Looks like that solved the issue for me. I think we can close this. Thanks

**Comment by osmankarame** [comment]
@ezequielc great thanks! @cameronreidrisevision it's fixed!
