### ISSUE TITLE
Anti-Bullying Month featured template displaying very zoomed in.

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/content-templates#105]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/100098797/193917416-9e32a57a-7c35-4af9-80f0-a4f1e03f0a3b.png">
 
October text is very zoomed and not displaying properly.

**Comment by mmeiers** [comment]
@cameronreidrisevision this is fixed.
