### ISSUE TITLE
Events Template

### ISSUE THREAD

**Issue by mawool01** [Rise-Vision/content-templates#86]
When adding more than 4 events to a google spreadsheet the events overlap on the Events.html page. Anyone know why?

**Comment by pcsandford** [comment]
Hi @mawool01 I just wanted to let you know that adding in functionality for more than 4 slides is currently in the backlog for this template, but for now I thought you may be interested in another template that we have produced here:  https://github.com/Rise-Vision/content-google-spreadsheet-events This one functions in a similar way, but in this case each event will slide in and out from the left of the screen, and as the transitions are controlled via JavaScript it can handle more than the 4 slides. 

Thanks!

Peter
