### ISSUE TITLE
Events Template, events do not pull from Sheet sequentially

### ISSUE THREAD

**Issue by acodega** [Rise-Vision/content-templates#89]
Have an interesting bug here..

**Reproduction Steps**
Duplicated the demo Google Sheet and deployed Events TV to S3

**Expected Results**
Events display sequentially. The event in row 2 of the spreadsheet will display, then row 3, then row 4.

**Actual Results**
The event in row 3 appears, then row 2, then row 5, then row 4, etc.

My URL is http://s3-us-west-2.amazonaws.com/swipelytv/events/events.html

**Comment by pcsandford** [comment]
Hi @acodega thanks for noting this. I think what might be causing it is that the template is currently using CSS animations to move the slides and at the moment this is configured for a maximum of 4 slides, so if you have 5+ events this might be the reason you are seeing the odd ordering effect. 

The template is due for an update to allow for any number of slides to be shown, and this is currently in the work backlog. For the moment, you mind find it helpful to check out the google-spreadsheet-events template here: https://github.com/Rise-Vision/content-google-spreadsheet-events which may have the functionality you are looking for. 

Thanks!

Peter
