### ISSUE TITLE
Alerts Template does not show your Alert.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/content-templates#90]
### What is the expected behavior?
When you send an alert, the text you have entered into your alert shows up in the Alert Presentation.

### What is the actual behavior?
The text that shows in the preview is what shows in your actual alert.

### What steps can be taken to replicate the problem?
1. Create a copy of the CAP Alert Warning Template.
2. Set that as your Alerts Presentation, and send an alert from E2Campus.
3. Notice that the content is from the Alert Preview, NOT your content.

Looking at the HTML of the Presentation , it shows this:
![2018-08-21_09-46-57](https://user-images.githubusercontent.com/6862256/44406294-41bdcc80-a529-11e8-82ab-ea7cb36a2c2b.png)

​It should be this:
![2018-08-21_09-47-35](https://user-images.githubusercontent.com/6862256/44406306-497d7100-a529-11e8-8360-a8fc50d84eb1.png)

**Comment by mmeiers** [comment]
@robb-price this has been fixed.

Just to confirm I corrected it in this presentation. Which I tracked back as the one that is in the store.
https://apps.risevision.com/editor/workspace/43382714-69d0-420b-b1ce-d019f0dfdb7b/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

**Comment by robb-price** [comment]
Verified and closed.
