### ISSUE TITLE
Bring peace to Ukraine does not scale to 4K on Firestick

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/content-templates#94]
What is the expected behavior from the user’s point of view?
The presentation should fill the display.

What is the actual behavior from the user’s point of view?
The flag only shows in the top corner on Firestick. Can't test on Android as my Android won't go 4K.

What steps can be taken to reproduce the actual behavior?
![PXL_20220420_190647799](https://user-images.githubusercontent.com/6862256/164304455-2a3f5f46-771a-40ca-a555-59a2ddba1918.jpg)

**Comment by santiagonoguez** [comment]
Will be fixed with https://github.com/Rise-Vision/android-player/issues/127

**Comment by santiagonoguez** [comment]
Validated and fixed on firestick device with 4K screen
