### ISSUE TITLE
Custom World Markets presentation does not update.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/content-templates#97]
What is the expected behavior from the user’s point of view?
The Presentation should continue working as it always has.

What is the actual behavior from the user’s point of view?
The presentation referenced below no longer updates throughout the day with the time. Previously, the times displays would stay in alignment with the current display time, in regards to their timezone. 

Have you been able to replicate the actual behavior and what steps can be taken to do so?
Yes, I have replicated it on my Windows display. 

Here is the presentation: https://apps.risevision.com/editor/workspace/279c9cd2-0388-4315-97ae-062497026fea?cid=56abb49b-3f91-470e-ac83-8bb107b1efb7

This does not appear to happen with our World Markets Clocks presentation, however ours does not have all the markets that they need to display.

**Comment by mmeiers** [comment]
@robb-price this is fixed
https://apps.risevision.com/templates/edit/511ccd15-dd0d-4359-a6e3-6387d043c4ad/?cid=56abb49b-3f91-470e-ac83-8bb107b1efb7

I fixed the code so there is no longer the need to manually refresh which caused the flash.
The Open and Closed labels now work based on time.
However this spreadsheet at one point factored for holidays:
https://docs.google.com/spreadsheets/d/1i0mEwbsvyaBAIjvEq-NJLSkrGN05AFrwTQF2Vflog8E/edit#gid=0

This is what has not been updated in 3 years. My suggestion is to not mention to the client as they obviously have been okay with it just not factoring in holidays for the last 3 years. If they do ever mention it I think we just need to give them the spreadsheet and say they are responsible for updating it.
