### ISSUE TITLE
Zoned Portrait Playlist 1x3 does not scale correctly on ChromeOS

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/content-templates#98]
What is the expected behavior from the user’s point of view?
The presentation should scale to fit a 4K portrait display correctly on Chrome OS

What is the actual behavior from the user’s point of view?
The Presentation only takes up the top corner of the display:
![PXL_20220817_223609046](https://user-images.githubusercontent.com/6862256/185255763-15fcc953-6bf5-4816-98e9-a6bc7dc3b25a.jpg)

Have you been able to replicate the actual behavior and what steps can be taken to do so?
Yes, but have only tested on the same OS the user is using; ChromeOS.

**Comment by osmankarame** [comment]
@robb-price I might have fixed the issue, but I'll need you ton confirm for me please, since I can't test it on a 4k portrait display. Thanks

**Comment by robb-price** [comment]
@osmankarame I will try and let you know.

**Comment by robb-price** [comment]
@osmankarame Unfortunately it looks like it is still happening.
