### ISSUE TITLE
Football Game - Sports template - Text size scroller cuts off a portion of text

### ISSUE THREAD

**Issue by cameronreidrisevision** [Rise-Vision/content-templates#99]
When adjusting the text sections' font sizes in this template, portions of the text will cut off.

![2022-09-09_08-30-54](https://user-images.githubusercontent.com/100098797/189396418-74277271-0796-46df-8384-869bad4dc0ad.png)

**Comment by mmeiers** [comment]
@cameronreidrisevision this was fixed.
